"""
This program allows the users to make a POST request first to pass
the text they want to be processed in the 'raw text' format, then
the user is allowed to get the entities information of the text via
different GET requests .
"""

from spacy import displacy
from flask import Flask, jsonify, request
import uuid
from Doc import Doc
from Catch import Catch


app = Flask(__name__)


catch = Catch()

@app.route('/list', methods=['POST'])
def list_all_entities():
    """POST request, generate a response listing the details of all the entities.

    Args:
        raw text: the user should post an article (raw text format) to this api.

    Returns:
        json: list the details of the entities in the article, in the json format
    """

    article = request.data.decode()
    my_doc = Doc(article)
    dic = []
    mapping = my_doc.map_position_start_index()

    for ent in my_doc.get_doc().ents:
        ent_dic = {}
        start_index = ent.start_char
        position = my_doc.get_position(start_index, mapping)
        label = my_doc.get_label(ent)

        ent_dic["entity"] = ent.text
        ent_dic["position"] = position
        ent_dic["label"] = label

        dic.append(ent_dic)
    return jsonify(dic)


@app.route('/post', methods=['POST'])
def visualization():
    """ POST request, can be made via Postman.

    Notes:
        the format of the body of the POST request must be 'raw text'.

    Args:
        raw text: the body of the POST request should be raw text.
    Returns:
        String: Return a URL containing the reference number of this POST, the user
        can use the URL in the browser to see the visualized entity extract result
    """
    article = request.data.decode()  # String

    my_doc = Doc(article)
    reference_number = str(uuid.uuid4())

    html = displacy.render(my_doc.get_doc(), style="ent")
    catch.add_reference(reference_number, html)

    return jsonify({
        'your reference':
            f"http://{request.host}/get?reference={reference_number}"
    })


@app.route('/get', methods=['GET'])
def get():
    """ Display the original text with labeled entities highlighted.

    Notes:
        Before using this GET request, the user must have used a POST request to
    get the URL in order to create a valid GET request.

    Args:
        String: the special ID created by the corresponding POST request.

    Returns:
        "Please enter valid reference."(String): if the reference number does not exist.
        "Please enter your reference."(String): if the user didn't pass a reference number.
        html(HTML): if the user passes a valid reference number.
    """
    if 'reference' in request.args:
        #reference_number is the UUID generated by every different POST.
        reference_number = request.args['reference']
        if reference_number in catch.references:
            html = catch.get_value(reference_number)
            return html
        return "Please enter valid reference."
    return "Please enter your reference."


if __name__ == '__main__':
    app.run(debug=True)